### ISSUE TITLE
Custom domain support

### ISSUE THREAD

**Issue by Conor-Burns** [drewdecarme/medusa-file-cloudflare-images#1]
Hi, I was intending to write this too, but you beat me to it 👍  great work!

Could you also try implementing this:
https://developers.cloudflare.com/images/cloudflare-images/serve-images#serving-images-from-custom-domains

Thanks in advance!

**Comment by drewdecarme** [comment]
Sure, what exactly are you trying to accomplish with the custom domains? Medusa should just save and serve up the Image URLs that are returned which is the image delivery URL

**Comment by Conor-Burns** [comment]
@drewdecarme I'd love to have the images come from the same domain as the frontend - pretty cosmetic I know😅

**Comment by drewdecarme** [comment]
Yeah sure, I can take a look at it when I get the chance. Might not be for some time, but I'll keep it on my radar.

Feel free to submit a PR too if you want to take a stab at it

**Comment by drewdecarme** [comment]
@Conor-Burns finally got the time to fix some bugs on this and get around to this request. I'm assuming you're looking for something like this right? https://developers.cloudflare.com/images/cloudflare-images/serve-images/#serving-images-from-custom-domains
