### ISSUE TITLE
[bug] depencies

### ISSUE THREAD

**Issue by adrien2p** [drewdecarme/medusa-file-cloudflare-images#2]
the interfaces package should not be part of both dependencies and peers but it should be moved from dependencies to devDependencies

https://github.com/drewdecarme/medusa-file-cloudflare-images/blob/1ebef06df8c5268456c70e6dffdecd012eeb35c8/package.json#L44

**Comment by drewdecarme** [comment]
Been a long time getting to this but I guess that's what happens when you have another child during COVID. Glad to get this fixed! Thanks for the issue @adrien2p
